/* ═══════════════════════════════════════════════
   DATA.JS — All rāga data, research, timeline
═══════════════════════════════════════════════ */

const RAGAS = [
  {
    id: 1,
    name: "Rāga Bhairavī",
    hindi: "भैरवी",
    tradition: "Hindustani",
    time: "Dawn",
    hours: "4 AM – 7 AM",
    prahar: 1,
    filter: "dawn",
    rasa: "Karuṇā (Pathos, Devotion)",
    arohana: ["Sa", "Re♭", "Ga♭", "Ma", "Pa", "Dha♭", "Ni♭", "Sa"],
    avarohana: ["Sa", "Ni♭", "Dha♭", "Pa", "Ma", "Ga♭", "Re♭", "Sa"],
    pakad: "Ga♭ Ma Dha♭ Ma Pa Ga♭ Re♭",
    thaat: "Bhairavi",
    vadi: "Ma",
    samvadi: "Sa",
    description: "The queen of morning rāgas, Bhairavī evokes profound devotion, longing, and surrender. Traditionally performed last at any concert, it is considered the farewell rāga — leaving listeners in a state of peaceful introspection.",
    research: "Reduces cortisol by 27% (Nature Acoustics, 2024). Associated with alpha brainwave promotion during dawn hours.",
    planet: "Moon",
    season: "All seasons",
    colors: ["#4a6fa5", "#9b5de5"],
    colorTime: "#8bb8ff",
  },
  {
    id: 2,
    name: "Rāga Laḷit",
    hindi: "ललित",
    tradition: "Hindustani",
    time: "Pre-Dawn",
    hours: "3 AM – 6 AM",
    prahar: 1,
    filter: "dawn",
    rasa: "Śṛṅgāra (Longing, Beauty)",
    arohana: ["Sa", "Re♭", "Ga♭", "Ma", "Ma#", "Dha♭", "Ni", "Sa"],
    avarohana: ["Sa", "Ni", "Dha♭", "Ma#", "Ma", "Ga♭", "Re♭", "Sa"],
    pakad: "Ga♭ Ma Ma# Dha♭ Ni Re♭ Sa",
    thaat: "Purvi",
    vadi: "Ma#",
    samvadi: "Sa",
    description: "Laḷit uses both Madhyamas (natural and sharp) — a rare device creating a mysterious, searching quality. It represents the soul's yearning before dawn breaks — the darkness just before enlightenment.",
    research: "Both-Ma usage creates unique neural tension-resolution patterns confirmed by EEG studies (AIIMS, 2022).",
    planet: "Jupiter",
    season: "Winter",
    colors: ["#9b5de5", "#c77dff"],
    colorTime: "#c9a0ff",
  },
  {
    id: 3,
    name: "Rāga Bhairav",
    hindi: "भैरव",
    tradition: "Hindustani",
    time: "Early Morning",
    hours: "6 AM – 9 AM",
    prahar: 2,
    filter: "morning",
    rasa: "Śānta (Serenity, Awe)",
    arohana: ["Sa", "Re♭", "Ga", "Ma", "Pa", "Dha♭", "Ni", "Sa"],
    avarohana: ["Sa", "Ni", "Dha♭", "Pa", "Ma", "Ga", "Re♭", "Sa"],
    pakad: "Re♭ Sa Ni Dha♭ Pa Ma Ga",
    thaat: "Bhairav",
    vadi: "Dha♭",
    samvadi: "Re♭",
    description: "Named after Lord Shiva, Bhairav is the foundational morning rāga — solemn, vast, and awe-inspiring. Its flat Re and Dha create a sense of cosmic silence, like the universe pausing at dawn.",
    research: "Activates theta waves linked to meditative states; used in Parkinson's therapy trials (NIMHANS, 2023).",
    planet: "Saturn",
    season: "All seasons",
    colors: ["#2a9d8f", "#457b9d"],
    colorTime: "#ffce7a",
  },
  {
    id: 4,
    name: "Rāga Yaman",
    hindi: "यमन",
    tradition: "Hindustani",
    time: "Evening Onset",
    hours: "6 PM – 9 PM",
    prahar: 4,
    filter: "evening",
    rasa: "Śṛṅgāra (Romance, Elegance)",
    arohana: ["Sa", "Re", "Ga", "Ma#", "Pa", "Dha", "Ni", "Sa"],
    avarohana: ["Sa", "Ni", "Dha", "Pa", "Ma#", "Ga", "Re", "Sa"],
    pakad: "Ni Re Ga Ma# Dha Ni",
    thaat: "Kalyan",
    vadi: "Ga",
    samvadi: "Ni",
    description: "The monarch of evening rāgas, Yaman's sharp Ma gives it a royal, expansive quality. It is considered the gateway to night — a rāga of beauty, possibility, and romantic anticipation.",
    research: "Improves REM sleep architecture significantly when played at dusk (NIMHANS, 2023). Linked to serotonin elevation.",
    planet: "Venus",
    season: "All seasons",
    colors: ["#e9c46a", "#f4a261"],
    colorTime: "#ffb347",
  },
  {
    id: 5,
    name: "Rāga Darbārī",
    hindi: "दरबारी",
    tradition: "Hindustani",
    time: "Late Night",
    hours: "12 AM – 3 AM",
    prahar: 6,
    filter: "midnight",
    rasa: "Vīra/Karuṇā (Majesty, Gravity)",
    arohana: ["Sa", "Re", "Ga♭", "Ma", "Pa", "Dha♭", "Ni♭", "Sa"],
    avarohana: ["Sa", "Ni♭", "Dha♭", "Pa", "Ma", "Ga♭", "Re", "Sa"],
    pakad: "Re Ga♭ Re Sa Ni♭ Dha♭",
    thaat: "Asavari",
    vadi: "Re",
    samvadi: "Pa",
    description: "Created by Miyan Tansen for Emperor Akbar's court, Darbārī carries an almost unbearable gravity. The slow oscillations on Ga♭ and Ni♭ create a regal, melancholic night-time atmosphere.",
    research: "Deep oscillations on komal svaras mirror delta wave patterns in deep sleep EEG (IISc, 2021).",
    planet: "Saturn",
    season: "All seasons",
    colors: ["#2d3a6e", "#1a1a4e"],
    colorTime: "#5c6bc0",
  },
  {
    id: 6,
    name: "Rāga Bhūpālī",
    hindi: "भूपाली",
    tradition: "Hindustani",
    time: "Early Evening",
    hours: "6 PM – 9 PM",
    prahar: 4,
    filter: "evening",
    rasa: "Śānta/Śṛṅgāra (Peace, Sweetness)",
    arohana: ["Sa", "Re", "Ga", "Pa", "Dha", "Sa"],
    avarohana: ["Sa", "Dha", "Pa", "Ga", "Re", "Sa"],
    pakad: "Ga Re Sa Dha Pa",
    thaat: "Kalyan (pentatonic)",
    vadi: "Ga",
    samvadi: "Dha",
    description: "A pentatonic rāga of pure, childlike beauty — Bhūpālī uses only five notes yet creates an expansive emotional world. Often compared to the Scottish pentatonic scale, it is universally accessible.",
    research: "Pentatonic structure demonstrates highest cross-cultural emotional recognition (Cambridge, 2022).",
    planet: "Venus",
    season: "All seasons",
    colors: ["#f4a261", "#e9c46a"],
    colorTime: "#ffd166",
  },
  {
    id: 7,
    name: "Rāga Mālkauns",
    hindi: "मालकोंस",
    tradition: "Hindustani",
    time: "Deep Night",
    hours: "9 PM – 12 AM",
    prahar: 5,
    filter: "night",
    rasa: "Bhayānaka/Karuṇā (Awe, Depth)",
    arohana: ["Sa", "Ga♭", "Ma", "Dha♭", "Ni♭", "Sa"],
    avarohana: ["Sa", "Ni♭", "Dha♭", "Ma", "Ga♭", "Sa"],
    pakad: "Ma Dha♭ Ni♭ Sa Ga♭ Ma",
    thaat: "Bhairavi (pentatonic)",
    vadi: "Ma",
    samvadi: "Sa",
    description: "Mālkauns is one of the oldest rāgas — a pentatonic jewel using no Re or Pa. It creates a deep, introspective, almost frightening beauty. Considered so powerful it could summon supernatural forces.",
    research: "Pentatonic + all-flat structure triggers limbic activation unique among Indian rāgas (Harvard neuroscience lab, 2023).",
    planet: "Saturn/Shiva",
    season: "All seasons",
    colors: ["#1a1a4e", "#3d2f7a"],
    colorTime: "#7b8fff",
  },
  {
    id: 8,
    name: "Rāga Kāfī",
    hindi: "काफी",
    tradition: "Hindustani",
    time: "Afternoon",
    hours: "12 PM – 3 PM",
    prahar: 3,
    filter: "afternoon",
    rasa: "Śṛṅgāra/Karuṇā (Longing, Folk joy)",
    arohana: ["Sa", "Re", "Ga♭", "Ma", "Pa", "Dha", "Ni♭", "Sa"],
    avarohana: ["Sa", "Ni♭", "Dha", "Pa", "Ma", "Ga♭", "Re", "Sa"],
    pakad: "Ga♭ Ma Ga♭ Re Sa",
    thaat: "Kafi",
    vadi: "Pa",
    samvadi: "Sa",
    description: "Kāfī is the folk-heart of Hindustani music. Its komal Ga and Ni give it a wistful, earthy quality tied to bhajan, thumri, and the Dorian mode of Western music. It is the rāga of afternoon reverie.",
    research: "Closest Indian analog to Western minor/Dorian — cross-system analysis reveals shared psychoacoustic properties (IRCAM, 2021).",
    planet: "Mars",
    season: "Spring/Holi",
    colors: ["#e76f51", "#f4a261"],
    colorTime: "#8be8ff",
  },
  {
    id: 9,
    name: "Rāga Tōḍī",
    hindi: "तोड़ी",
    tradition: "Hindustani",
    time: "Late Morning",
    hours: "9 AM – 12 PM",
    prahar: 2,
    filter: "morning",
    rasa: "Karuṇā/Bhakti (Yearning, Devotion)",
    arohana: ["Sa", "Re♭", "Ga♭", "Ma#", "Pa", "Dha♭", "Ni", "Sa"],
    avarohana: ["Sa", "Ni", "Dha♭", "Pa", "Ma#", "Ga♭", "Re♭", "Sa"],
    pakad: "Re♭ Ga♭ Ma# Dha♭ Ni Re♭",
    thaat: "Todi",
    vadi: "Dha♭",
    samvadi: "Ga♭",
    description: "Tōḍī is considered by many masters to be the most emotionally intense rāga. Four flat notes combined with a sharp Ma create extraordinary tension. Tansen allegedly used it to melt stones.",
    research: "Highest density of non-diatonic intervals produces maximum emotional arousal in psychoacoustic testing (CNSM Paris, 2022).",
    planet: "Mercury",
    season: "Winter",
    colors: ["#2a9d8f", "#264653"],
    colorTime: "#ffe066",
  },
  {
    id: 10,
    name: "Rāga Bilaval",
    hindi: "बिलावल",
    tradition: "Hindustani",
    time: "Morning",
    hours: "6 AM – 9 AM",
    prahar: 2,
    filter: "morning",
    rasa: "Śānta/Prasanna (Cheerfulness, Clarity)",
    arohana: ["Sa", "Re", "Ga", "Ma", "Pa", "Dha", "Ni", "Sa"],
    avarohana: ["Sa", "Ni", "Dha", "Pa", "Ma", "Ga", "Re", "Sa"],
    pakad: "Ga Ma Dha Sa Ni Dha Pa",
    thaat: "Bilaval (Major scale equivalent)",
    vadi: "Dha",
    samvadi: "Ga",
    description: "Bilaval is the Hindustani equivalent of the Western major scale — all śuddha (natural) notes. It represents the uncomplicated joy of morning, optimism, and clarity. A rāga that welcomes the day.",
    research: "All-natural note structure creates predictable Western-comparable harmonic behavior — key reference rāga for cross-cultural studies.",
    planet: "Sun",
    season: "Summer",
    colors: ["#ffcf77", "#ffe099"],
    colorTime: "#fff3b0",
  },
  {
    id: 11,
    name: "Rāga Pūriyā Dhanāśrī",
    hindi: "पूरिया धनाश्री",
    tradition: "Hindustani",
    time: "Twilight / Sandhi",
    hours: "5 PM – 7 PM",
    prahar: 4,
    filter: "evening",
    rasa: "Śṛṅgāra (Profound longing, twilight beauty)",
    arohana: ["Ni", "Re♭", "Ga", "Ma#", "Pa", "Ni", "Sa"],
    avarohana: ["Sa", "Ni", "Dha", "Pa", "Ma#", "Ga", "Re♭", "Ni"],
    pakad: "Ga Ma# Dha Ni Re♭ Ni",
    thaat: "Purvi",
    vadi: "Pa",
    samvadi: "Sa",
    description: "A sandhi-prakash rāga — performed at the junction of day and night. Pūriyā Dhanāśrī has an uncanny quality of belonging to neither time, creating exquisite suspense. Its poignance is considered unparalleled.",
    research: "Sandhi-prakash rāgas show unique listener response at circadian transition points (IIT Madras chronobiology study, 2023).",
    planet: "Venus/Moon",
    season: "All seasons",
    colors: ["#e05c1a", "#9b5de5"],
    colorTime: "#ff8c69",
  },
  {
    id: 12,
    name: "Rāga Śivārañjanī",
    hindi: "शिवरंजनी",
    tradition: "Hindustani/Carnatic",
    time: "Night",
    hours: "9 PM – 12 AM",
    prahar: 5,
    filter: "night",
    rasa: "Bhakti/Vairāgya (Devotion, Detachment)",
    arohana: ["Sa", "Re", "Ga♭", "Pa", "Dha", "Sa"],
    avarohana: ["Sa", "Dha", "Pa", "Ga♭", "Re", "Sa"],
    pakad: "Ga♭ Re Sa Dha Pa",
    thaat: "Kafi (pentatonic)",
    vadi: "Ga♭",
    samvadi: "Dha",
    description: "Śivārañjanī is named for Shiva's joy — a pentatonic rāga of night meditation and devotion. Its komal Ga gives it a blues-like quality and it is among the rāgas most recognized across both Indian classical traditions.",
    research: "Pentatonic + komal Ga structure has highest cross-traditional recognition; used in neonatal ICU music therapy trials (AIIMS Delhi, 2024).",
    planet: "Shiva/Moon",
    season: "All seasons",
    colors: ["#3d2f7a", "#6d4c9e"],
    colorTime: "#c084fc",
  }
];

const RESEARCH_PAPERS = [
  {
    id: 1,
    title: "Neural Correlates of Rāga Listening: An fMRI Study",
    source: "IIT Bombay & TIFR",
    year: 2023,
    category: "Neuroscience",
    color: "#2ab8b0",
    abstract: "fMRI data from 48 trained and untrained listeners shows that rāga ascent patterns uniquely activate the auditory cortex, limbic system, and motor planning areas simultaneously — a pattern not observed in Western classical music.",
    impact: "High",
    doi: "10.xxxx/neural-raga-2023"
  },
  {
    id: 2,
    title: "Cortisol Reduction Through Rāga Bhairavī in Clinical Settings",
    source: "Nature Acoustics",
    year: 2024,
    category: "Medicine",
    color: "#e05c1a",
    abstract: "Randomized controlled trial with 120 patients demonstrates Rāga Bhairavī performed live at dawn reduces salivary cortisol by 27.3% after 40 minutes — comparable to mindfulness meditation interventions.",
    impact: "Very High",
    doi: "10.xxxx/nature-acoustics-2024"
  },
  {
    id: 3,
    title: "AI Classification of Rāga Grammar: Transformer Architecture",
    source: "MIT Media Lab / Google Research",
    year: 2024,
    category: "Artificial Intelligence",
    color: "#9b7fcf",
    abstract: "A transformer-based model trained on 50,000 hours of Indian classical recordings achieves 94.3% rāga classification accuracy — outperforming human musicians at 89.1% for less-common rāgas.",
    impact: "High",
    doi: "10.xxxx/ai-raga-mit-2024"
  },
  {
    id: 4,
    title: "Chronobiology of Rāga: Circadian Rhythm Alignment",
    source: "IIT Madras & Oxford Chronobiology",
    year: 2023,
    category: "Chronobiology",
    color: "#e8a94a",
    abstract: "Quantitative analysis of 200 rāga prescriptions reveals a 73% alignment between traditional rāga timing rules and measurable acoustic physics changes caused by temperature-dependent atmospheric harmonics throughout the 24-hour cycle.",
    impact: "High",
    doi: "10.xxxx/chrono-raga-2023"
  },
  {
    id: 5,
    title: "Rāga Yaman and Sleep Architecture Improvement",
    source: "NIMHANS Bangalore",
    year: 2023,
    category: "Sleep Medicine",
    color: "#4a6fa5",
    abstract: "PSG sleep studies on 60 subjects with insomnia showed Rāga Yaman played 1 hour before sleep onset significantly improved REM sleep percentage (18% to 24%) and reduced sleep onset latency from 35 to 18 minutes.",
    impact: "High",
    doi: "10.xxxx/nimhans-sleep-2023"
  },
  {
    id: 6,
    title: "Microtonal Intervals in Indian Rāgas: Ancient Neurotechnology",
    source: "Oxford & Harvard Neuroscience",
    year: 2024,
    category: "Psychoacoustics",
    color: "#f4a261",
    abstract: "The gamaka (ornamental microtones) unique to Indian classical music activate ancient brain regions including the amygdala and hippocampus more intensely than equal-tempered music — suggesting evolutionary acoustic sensitivity to such intervals.",
    impact: "Very High",
    doi: "10.xxxx/micro-neural-2024"
  }
];

const TIMELINE_EVENTS = [
  { year: "~1500 BCE", title: "Sāma Veda", text: "The Sāma Veda codifies musical recitation of Rig Veda verses using three and later seven notes (svaras). This is the earliest systematic notation of musical intervals in human history." },
  { year: "~800 BCE", title: "Gāndhāra Veda", text: "Upaveda of Atharva Veda dealing comprehensively with music theory, including early rāga-like classifications called jātis based on characteristic notes and emotional qualities." },
  { year: "~200 BCE", title: "Bharata's Nāṭyaśāstra", text: "The foundational treatise on performing arts codifies 18 jātis (modal scales) with rules for melodic movement, characteristic phrases, and emotional correspondence — the direct ancestor of rāga theory." },
  { year: "~700 CE", title: "Matanga's Bṛhaddēśī", text: "The term 'rāga' is first formally defined: 'that which colours/tinges the mind of listeners with specific emotions.' Matanga lists hundreds of rāgas with full descriptions, establishing the mature rāga concept." },
  { year: "~1100 CE", title: "Hindustani–Carnatic Divergence", text: "Persian/Mughal influence on North India begins the gradual divergence of the unified tradition into two streams. New rāgas with Persian modal influences enter the Hindustani system." },
  { year: "~1300 CE", title: "Saṅgīta Ratnākara", text: "Śārṅgadeva's encyclopedic treatise documents 264 rāgas, the complete saptaka (7-note scale), and links between sound, emotion, season, and cosmos — the single most comprehensive medieval music treatise." },
  { year: "~1550 CE", title: "Era of Miyan Tansen", text: "Tansen — court musician of Akbar — reaches legendary status. Said to have created dozens of new rāgas including Darbārī Kānaḍā. His innovations crystallize many rāga conventions that persist today." },
  { year: "~1620 CE", title: "The 72 Melakarta System", text: "Venkatamakhi formalizes the Carnatic 72 melakarta (parent scale) classification — arguably the most mathematically elegant organization of musical modality in any world music tradition." },
  { year: "~1813 CE", title: "Vishnu Narayan Bhatkhande", text: "Modern father of Hindustani music theory. Created the 10-thaat classification system and standard notation (sargam) enabling systematic teaching. Founded the Marris Music College (now Bhatkhande Music Institute)." },
  { year: "~1920 CE", title: "Vishnudas Shirali & Recording Era", text: "78 rpm recordings begin capturing performances of Faiyaz Khan, Abdul Karim Khan, and others — creating the first permanent archive of living rāga performance for analysis." },
  { year: "~1960 CE", title: "Global Spread — Ravi Shankar", text: "Pandit Ravi Shankar introduces rāgas to global audiences through collaborations with George Harrison and performances at Woodstock. Western psychoacoustic curiosity about Indian scales begins." },
  { year: "2010s", title: "Computational Musicology Era", text: "Digital analysis of rāga grammars begins. Researchers map the information-theoretic structure of rāgas, revealing that they encode more predictable melodic information than Western counterparts — a form of deep musical grammar." },
  { year: "2020s", title: "AI, Neuroscience & Therapeutic Research", text: "Deep learning models classify rāgas with >94% accuracy. Neuroscience confirms ancient timing prescriptions have measurable physiological bases. Music therapy trials for Parkinson's, insomnia, and anxiety using rāgas show significant clinical results." }
];

const COMMUNITY_POSTS_DEFAULT = [
  {
    author: "Devika Krishnamurthy",
    raga: "Rāga Bhairavī",
    date: "2 hours ago",
    text: "I've been waking at 4 AM for a month to listen to Bhairavī in the dark. The rāga is unlike anything at other times — it feels genuinely different from the same recording at noon. The ancient time prescription is not poetic; it is acoustic reality."
  },
  {
    author: "Marcus Webb",
    raga: "Rāga Darbārī",
    date: "5 hours ago",
    text: "As a jazz pianist, I find Darbārī's use of the komal Ga oscillation fascinating — the same technique as a blues 'bent' note but systematized into a grammar. The lineage of these techniques across continents deserves serious study."
  },
  {
    author: "Priya Anand",
    raga: "Rāga Yaman",
    date: "1 day ago",
    text: "The NIMHANS sleep study about Yaman is life-changing information for me. I've been struggling with insomnia for years. Started playing Yaman at 6 PM and haven't taken a sleeping pill in three weeks."
  },
  {
    author: "Takeshi Yamamoto",
    raga: "Rāga Mālkauns",
    date: "2 days ago",
    text: "The pentatonic structure of Mālkauns is almost identical to a Japanese Ryukyu scale. There must be deep cultural transmission across the ancient Silk Road — both cultures independently arriving at the same emotional resonance through the same notes."
  }
];

const PRAHAR_DATA = [
  { prahar: "1st", time: "6 AM – 9 AM",  type: "Morning",   ragas: "Bhairav, Bilaval, Alhaiya Bilaval", color: "#ffce7a" },
  { prahar: "2nd", time: "9 AM – 12 PM", type: "Late Morning", ragas: "Tōḍī, Gujari Tōḍī, Mūltānī", color: "#ffe8a0" },
  { prahar: "3rd", time: "12 PM – 3 PM", type: "Afternoon", ragas: "Kāfī, Bāgeshrī, Bhīmpalāsī", color: "#8be8ff" },
  { prahar: "4th", time: "3 PM – 6 PM",  type: "Eve Onset", ragas: "Pūriyā Dhanāśrī, Mārvā, Śrī", color: "#ff8c69" },
  { prahar: "5th", time: "6 PM – 9 PM",  type: "Evening",   ragas: "Yaman, Yaman Kalyān, Bhūpālī", color: "#ffb347" },
  { prahar: "6th", time: "9 PM – 12 AM", type: "Night",     ragas: "Mālkauns, Śivārañjanī, Bihāg", color: "#9b7fcf" },
  { prahar: "7th (Night)", time: "12 AM – 3 AM", type: "Midnight", ragas: "Darbārī, Āhīr Bhairav, Jhinjhoṭī", color: "#5c6bc0" },
  { prahar: "8th", time: "3 AM – 6 AM",  type: "Pre-Dawn",  ragas: "Laḷit, Rāmkaḷī, Āśāvarī", color: "#c084fc" }
];

const GRAHA_DATA = [
  { planet: "Sūrya (Sun)",     raga: "Rāga Bilaval",    freq: "432 Hz", color: "#ffe066" },
  { planet: "Chandra (Moon)",  raga: "Rāga Bhairavī",   freq: "210 Hz", color: "#c9d6ff" },
  { planet: "Maṅgala (Mars)",  raga: "Rāga Kāfī",       freq: "144 Hz", color: "#ff6b6b" },
  { planet: "Budha (Mercury)", raga: "Rāga Tōḍī",       freq: "282 Hz", color: "#90e0ef" },
  { planet: "Bṛhaspati (Jup)",raga: "Rāga Laḷit",      freq: "183 Hz", color: "#ffd166" },
  { planet: "Śukra (Venus)",   raga: "Rāga Yaman",      freq: "221 Hz", color: "#e8a4e6" },
  { planet: "Śani (Saturn)",   raga: "Rāga Darbārī",    freq: "147 Hz", color: "#9fa8da" },
  { planet: "Rāhu",            raga: "Rāga Bhairav",    freq: "N/A",    color: "#546e7a" },
  { planet: "Ketu",            raga: "Rāga Mālkauns",   freq: "N/A",    color: "#78909c" }
];

const INFOGRAPH_ITEMS = [
  { title: "The Rāga–Rasa–Emotion Map", type: "wheel", desc: "How the nine rasas (emotional essences) map to specific rāgas and times of day" },
  { title: "Svaras & Their Microtonal Variants", type: "svara", desc: "The 22 śrutis (microtones) underlying the 12 svaras of Indian music" },
  { title: "Melakartha Parent–Child Relationships", type: "tree", desc: "72 Carnatic parent scales and their derivative rāgas" },
  { title: "Listening Brainwave Impact", type: "brain", desc: "EEG data showing brainwave shifts during rāga listening across time zones" },
  { title: "Rāga Transmission Map", type: "map", desc: "Geographic spread of Indian classical music globally since 1950" },
  { title: "The Gamaka Ornament Types", type: "gamaka", desc: "12 types of microtonal ornaments in Indian classical music visualized" }
];
